apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flame-mcp-server.fullname" . }}-secret
  labels:
    {{- include "flame-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openai.apiKey }}
  openai-api-key: {{ .Values.secrets.openai.apiKey | b64enc | quote }}
  {{- else }}
  openai-api-key: {{ required "Azure OpenAI API Key is required" .Values.secrets.openai.apiKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.openai.apiBase }}
  openai-api-base: {{ .Values.secrets.openai.apiBase | b64enc | quote }}
  {{- else }}
  openai-api-base: {{ required "Azure OpenAI API Base URL is required" .Values.secrets.openai.apiBase | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.qdrant.token }}
  qdrant-token: {{ .Values.secrets.qdrant.token | b64enc | quote }}
  {{- end }} 